### PR TITLE
boot: remove fih delay rng inclusion

### LINKED ISSUE #831: zephyr: FIH brakes CONFIG_SINGLE_APPLICATION_SLOT
build is broken while CONFIG_SINGLE_APPLICATION_SLOT=y
``` console
west build -d build/mcuboot -b nrf52840dk_nrf52840 ./bootloader/mcuboot/boot/zephyr/ -t menuconfig
/* set CONFIG_SINGLE_APPLICATION_SLOT=y */
west build -d build/mcuboot -b nrf52840dk_nrf52840 ./bootloader/mcuboot/boot/zephyr/
...
...
...
eabi/bin/ld: app/libapp.a(single_loader.c.obj): in function `fih_delay_init':
/home/anpu/codedev/zephyrproject/bootloader/mcuboot/boot/bootutil/include/bootutil/fault_injection_hardening.h:174: multiple definition of `fih_delay_init'; app/libapp.a(main.c.obj):/home/anpu/codedev/zephyrproject/bootloader/mcuboot/boot/bootutil/include/bootutil/fault_injection_hardening.h:174: first defined here
collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by nvlsianpu**
Direct inclusion of "bootutil/fault_injection_hardening_delay_rng.h"
causes linking collision as this header belongs to `FIH_ENABLE_DELAY`
mode.
This header is already included by "bootutil/fault_injection_hardening.h"
appropriately.

fixes #831

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Comment by tamasban** [comment]
Actually the `bootutil/fault_injection_hardening_delay_rng.h` header also directly included from other files as well:
- cypress/MCUBootApp/main.c
- zephyr/src/main.c
- mynewt/src/main.c

Are the same build error present there as well?

**Comment by nvlsianpu** [comment]
I didn't test cypres and mynewt, but for zephyr mcuboot that was not an issue. Anyway - will correct in all places then/

**Comment by nvlsianpu** [comment]
@tamasban ^^

File: boot/bootutil/src/fault_injection_hardening_delay_rng_mbedtls.c [hunk 1]
```diff
@@ -8,7 +8,6 @@
 
 #ifdef FIH_ENABLE_DELAY
 
-#include "bootutil/fault_injection_hardening_delay_rng.h"
```
Comment (tamasban) [inline boot/bootutil/src/fault_injection_hardening_delay_rng_mbedtls.c:11]: I think it should be kept here.

**Comment by tamasban** [comment]
Look okay to me!

**Comment by nvlsianpu** [comment]
@tamasban 
> Looks okay to me!

Can you approve?

**Review by utzig — APPROVED** [review]

**Review by tamasban — APPROVED** [review]
